"""Libero-parity robot control API for MolmoSpaces environments.

Provides the same control primitives as FrankaLiberoApi (goto_pose, open/close
gripper, sample_grasp_pose, get_object_pose, etc.) backed by the real
MolmoSpaces MuJoCo simulator via FrankaMolmoSpacesEnv.
"""

from __future__ import annotations

import logging
import pathlib
from typing import Any

import numpy as np
from scipy.spatial.transform import Rotation as SciRotation

from rats.envs.base import BaseEnv
from rats.integrations.base_api import ApiBase
from rats.integrations.franka.molmospaces_frames import (
    grasp_site_quat_to_panda_hand_quat,
    validate_robot_base_pose,
    world_pose_to_robot_base_frame,
)
from rats.integrations.franka.perception_mixin import FrankaPerceptionMixin

logger = logging.getLogger(__name__)


class FrankaMolmoSpacesControlApi(FrankaPerceptionMixin, ApiBase):
    """Robot control helpers for Franka in MolmoSpaces environments.

    Mirrors the FrankaLiberoApi interface so that code-as-policy programs
    generated by the LLM work identically across Libero and MolmoSpaces.
    """

    # _TCP_OFFSET = -0.155 m is inherited from FrankaPerceptionMixin — the
    # geometric distance from panda_hand (IK target) to the Robotiq
    # grasp_site reported by the franka_droid sim. See the mixin docstring
    # for the derivation.

    def __init__(self, env: BaseEnv, use_sam3: bool = True) -> None:
        ApiBase.__init__(self, env)
        self.camera_name = "agentview"
        self.wrist_camera_name = "robot0_eye_in_hand"
        self.output_dir = pathlib.Path(".")
        self._init_perception(use_sam3=use_sam3)

    def functions(self) -> dict[str, Any]:
        return {
            "get_observation": self.get_observation,
            "get_object_pose": self.get_object_pose,
            "sample_grasp_pose": self.sample_grasp_pose,
            "goto_pose": self.goto_pose,
            "open_gripper": self.open_gripper,
            "close_gripper": self.close_gripper,
            "get_oriented_bounding_box_from_3d_points": self.get_oriented_bounding_box_from_3d_points,
            "get_object_3d_points_and_masks_from_language": self.get_object_3d_points_and_masks_from_language,
            "goto_home_joint_position": self.goto_home_joint_position,
        }

    def get_observation(self) -> dict[str, Any]:
        """Get the current observation from the environment.

        Returns:
            observation:
                A dictionary containing the observation of the environment.
                The dictionary contains the following keys:
                - ["agentview"]["images"]["rgb"]: Current color camera image as a numpy array of shape (H, W, 3), dtype uint8.
                - ["agentview"]["images"]["depth"]: Current depth camera image as a numpy array of shape (H, W), dtype float32.
                - ["agentview"]["intrinsics"]: Camera intrinsic matrix as a numpy array of shape (3, 3), dtype float64.
                - ["agentview"]["pose_mat"]: Camera extrinsic matrix as a numpy array of shape (4, 4), dtype float64.
                - ["robot0_eye_in_hand"]["images"]["rgb"]: Current wrist camera image as a numpy array of shape (H, W, 3), dtype uint8.
                - ["robot0_eye_in_hand"]["images"]["depth"]: Current wrist camera depth image as a numpy array of shape (H, W), dtype float32.
                - ["robot0_eye_in_hand"]["intrinsics"]: Wrist camera intrinsic matrix as a numpy array of shape (3, 3), dtype float64.
                - ["robot0_eye_in_hand"]["pose_mat"]: Wrist camera extrinsic matrix as a numpy array of shape (4, 4), dtype float64.
                - ["robot_cartesian_pos"]: Current end-effector (panda_hand) pose as a numpy array of shape (8,), dtype float64. The first 3 elements are XYZ, the next 4 are quaternion wxyz, the last is gripper position normalized 0 (closed) to 1 (open).
                - ["robot_joint_pos"]: Current joint positions as a numpy array of shape (8,), dtype float64. 7 joints + 1 gripper normalized.
        """
        obs = self._env.get_observation()
        for cam_name in [self.camera_name, self.wrist_camera_name]:
            if cam_name in obs and "images" in obs[cam_name]:
                depth = obs[cam_name]["images"].get("depth")
                if depth is not None and depth.ndim == 3:
                    obs[cam_name]["images"]["depth"] = depth.squeeze(-1)
        return obs

    def goto_pose(
        self, position: np.ndarray, quaternion_wxyz: np.ndarray, z_approach: float = 0.0
    ) -> None:
        """Go to pose using Inverse Kinematics.

        There is no need to call a second goto_pose with the same position and
        quaternion_wxyz after calling it with z_approach.

        Args:
            position: (3,) XYZ in meters.
            quaternion_wxyz: (4,) WXYZ unit quaternion.
            z_approach: Z-axis distance offset for approach motion. Will first arrive
                at position + z_approach meters in Z-axis before moving to the
                requested pose. Default is 0.0.

        Returns:
            None
        """
        pos_world = np.asarray(position, dtype=np.float64).reshape(3)
        quat_world_wxyz = np.asarray(quaternion_wxyz, dtype=np.float64).reshape(4)
        self._publish_robot_reach_target(
            pos_world,
            quat_world_wxyz,
            label="goto_pose_target",
        )
        try:
            robot_base_pose = validate_robot_base_pose(
                self.get_observation().get("robot_base_pose"),
            )
            pos, quat_wxyz = world_pose_to_robot_base_frame(
                pos_world,
                quat_world_wxyz,
                robot_base_pose,
            )
            self._record_runtime_diagnostic(
                "goto_pose_frame_transform",
                position_world=pos_world,
                quaternion_world_wxyz=quat_world_wxyz,
                robot_base_pose=robot_base_pose,
                position_base=pos,
                quaternion_base_wxyz=quat_wxyz,
            )
        except Exception as exc:
            self._record_runtime_diagnostic(
                "missing_or_invalid_robot_base_pose",
                reason=str(exc),
                robot_base_pose=self.get_observation().get("robot_base_pose"),
            )
            raise ValueError(f"Invalid robot_base_pose for MolmoSpaces goto_pose: {exc}") from exc

        quat_xyzw = np.array(
            [quat_wxyz[1], quat_wxyz[2], quat_wxyz[3], quat_wxyz[0]], dtype=np.float64
        )
        rot = SciRotation.from_quat(quat_xyzw)
        offset_pos = pos + rot.apply(self._TCP_OFFSET)

        # The IK URDF (panda_description) targets panda_hand, but the sim
        # reports grasp_site (= panda_hand @ Rz(+45°) given the full mounting
        # chain: panda_hand_joint rpy="0 0 -π/4" + the Robotiq <frame
        # quat="0.7071068 0 0 0.7071068"> wrapping the <attach> + grasp_site
        # xyaxes="0 -1 0 1 0 0"). The LLM-facing API interprets quaternion_wxyz
        # as the desired grasp_site orientation (consistent with how
        # robot_cartesian_pos[3:7] is reported), so we pre-rotate by Rz(-45°)
        # in the target's local frame to recover the panda_hand orientation
        # the IK actually needs. Position offset is unchanged: Rz preserves
        # the local Z axis along which _TCP_OFFSET points.
        quat_ik_wxyz = grasp_site_quat_to_panda_hand_quat(quat_wxyz)

        if z_approach != 0.0:
            z_offset_pos = offset_pos + rot.apply(np.array([0, 0, -z_approach]))

            if self.cfg is None:
                self.cfg = self._pks.solve_ik(
                    robot=self._robot,
                    target_link_name=self._target_link_name,
                    target_position=z_offset_pos,
                    target_wxyz=quat_ik_wxyz,
                )
            else:
                self.cfg = self._pks.solve_ik_vel_cost(
                    robot=self._robot,
                    target_link_name=self._target_link_name,
                    target_position=z_offset_pos,
                    target_wxyz=quat_ik_wxyz,
                    prev_cfg=self.cfg,
                )
            joints_z_offset = np.asarray(self.cfg[:-1], dtype=np.float64).reshape(7)
            self._env.move_to_joints_blocking(joints_z_offset)

        if self.cfg is None:
            self.cfg = self._pks.solve_ik(
                robot=self._robot,
                target_link_name=self._target_link_name,
                target_position=offset_pos,
                target_wxyz=quat_ik_wxyz,
            )
        else:
            self.cfg = self._pks.solve_ik_vel_cost(
                robot=self._robot,
                target_link_name=self._target_link_name,
                target_position=offset_pos,
                target_wxyz=quat_ik_wxyz,
                prev_cfg=self.cfg,
            )
        joints = np.asarray(self.cfg[:-1], dtype=np.float64).reshape(7)
        self._env.move_to_joints_blocking(joints)

        self._log_tcp_pose_delta(
            requested_world_pos=pos_world,
            requested_world_quat_wxyz=quat_world_wxyz,
        )

    def _publish_robot_reach_target(
        self,
        position_world: np.ndarray,
        quaternion_world_wxyz: np.ndarray | None = None,
        *,
        label: str = "reach_target",
    ) -> None:
        """Best-effort WebUI/Viser marker for the commanded reach target."""
        publisher = getattr(self, "_viser_publisher", None)
        published = False
        if publisher is not None:
            try:
                published = bool(
                    publisher.publish_robot_target(
                        position_world,
                        quaternion_wxyz=quaternion_world_wxyz,
                        label=label,
                    )
                )
            except Exception:
                published = False
        self._record_runtime_diagnostic(
            "robot_reach_target",
            position_world=np.asarray(position_world, dtype=np.float64).reshape(3),
            quaternion_world_wxyz=(
                np.asarray(quaternion_world_wxyz, dtype=np.float64).reshape(4)
                if quaternion_world_wxyz is not None
                else None
            ),
            label=label,
            viser_published=published,
        )

    def _log_tcp_pose_delta(
        self,
        *,
        requested_world_pos: np.ndarray,
        requested_world_quat_wxyz: np.ndarray,
    ) -> None:
        """Compare commanded world EE pose to the simulator's grasp_site pose.

        Reads ``robot_cartesian_pos`` from ``get_observation()`` — the bridge
        builds it from ``arm_mg.leaf_frame_to_world`` on the server, so this
        works in both the in-process and remote-bridge configurations. A
        persistent positive Z delta indicates the IK URDF (panda_hand) and the
        simulated robot (franka_droid + Robotiq) disagree on flange-to-tip
        offset.
        """
        actual_pos: np.ndarray | None = None
        actual_quat_wxyz: np.ndarray | None = None
        source = None

        try:
            obs = self.get_observation()
            cart = obs.get("robot_cartesian_pos")
            if cart is not None:
                cart_arr = np.asarray(cart, dtype=np.float64).reshape(-1)
                if cart_arr.size >= 7:
                    actual_pos = cart_arr[:3]
                    actual_quat_wxyz = cart_arr[3:7]
                    source = "robot_cartesian_pos"
        except Exception as exc:
            logger.warning("goto_pose TCP debug: failed to read observation: %s", exc)

        if actual_pos is None:
            bridge = getattr(self._env, "_real_bridge", None)
            if bridge is not None and hasattr(bridge, "robot_view"):
                try:
                    arm_mg = bridge.robot_view.get_move_group("arm")
                    tcp_mat = np.asarray(arm_mg.leaf_frame_to_world, dtype=np.float64)
                    if tcp_mat.shape == (4, 4):
                        actual_pos = tcp_mat[:3, 3]
                        actual_quat_xyzw = SciRotation.from_matrix(tcp_mat[:3, :3]).as_quat()
                        actual_quat_wxyz = np.array(
                            [actual_quat_xyzw[3], actual_quat_xyzw[0], actual_quat_xyzw[1], actual_quat_xyzw[2]],
                            dtype=np.float64,
                        )
                        source = "leaf_frame_to_world"
                except Exception as exc:
                    logger.warning(
                        "goto_pose TCP debug: leaf_frame_to_world unavailable: %s", exc
                    )

        if actual_pos is None or actual_quat_wxyz is None:
            return

        pos_delta = actual_pos - np.asarray(requested_world_pos, dtype=np.float64)
        req_quat = np.asarray(requested_world_quat_wxyz, dtype=np.float64)
        dot = float(np.clip(abs(req_quat @ actual_quat_wxyz), -1.0, 1.0))
        ang_err_rad = 2.0 * np.arccos(dot)

        logger.info(
            "goto_pose TCP delta [%s]: requested_pos=%s actual_grasp_site=%s "
            "delta=%s |delta|=%.4fm |delta_z|=%.4fm angle_err=%.2fdeg",
            source,
            np.round(requested_world_pos, 4).tolist(),
            np.round(actual_pos, 4).tolist(),
            np.round(pos_delta, 4).tolist(),
            float(np.linalg.norm(pos_delta)),
            float(abs(pos_delta[2])),
            float(np.degrees(ang_err_rad)),
        )
        self._record_runtime_diagnostic(
            "goto_pose_tcp_delta",
            source=source,
            requested_world_pos=requested_world_pos,
            requested_world_quat_wxyz=requested_world_quat_wxyz,
            actual_grasp_site_pos=actual_pos,
            actual_grasp_site_quat_wxyz=actual_quat_wxyz,
            position_delta=pos_delta,
            position_delta_norm=float(np.linalg.norm(pos_delta)),
            position_delta_z=float(pos_delta[2]),
            orientation_error_deg=float(np.degrees(ang_err_rad)),
        )

    def open_gripper(self) -> None:
        """Open gripper fully.

        Args:
            None
        """
        self._env._set_gripper(1.0)
        for _ in range(40):
            self._env._step_once()

    def close_gripper(self) -> None:
        """Close gripper fully.

        Args:
            None
        """
        self._env._set_gripper(0.0)
        for _ in range(60):
            self._env._step_once()

    def goto_home_joint_position(self) -> None:
        """Return the arm to its reset joint configuration with high manipulability."""
        home = getattr(self._env, "home_joint_position", None)
        if home is None:
            raise RuntimeError("Home joint position is unavailable in the current environment.")
        joints = np.asarray(home, dtype=np.float64).reshape(7)
        self._env.move_to_joints_blocking(joints)
